config/routes.rb
Rails.application.routes.draw do
  
  root "departments#index"

  resources :departments do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
  @department = Department.find(params[:id])
  end

  private

  def department_params
    params.require(:department).permit(:name)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :update, :edit, :destroy]
  
  def show
  end

  def index
    @items = @department.items
  end

  def edit
    render partial: "form"
  end

  def new
    @items = @department.items.new
    render partial: "form"
  end
  
  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def update
    if @item.update(items_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end


  def destroy
    @item.destroy
    redirect_to department_items_path
  end

  private

  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :price)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Welcome to the Department Store </h1>
<ul>
<% @departments.each do |department| %>
  <li> <%= link_to department.name, department_items_path(department) %></li>
  <% end %> 
</ul>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h1>Departments#show</h1>
<p>Find me in app/views/departments/show.html.erb</p>

app/views/items/_form.html.erb
<h1><%= @items.id ? "Edit Items" : "New Items" %></h1>
<hr />
<br />
<%= form_for [@department, @items] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name" %>
  <br />
  <br />
  <%= f.label :description %>
  <%= f.text_area :description, required: true, placeholder: "Description..." %>
  <br />
  <br />
  <%= f.label :price %>
  <%= f.text_field :price, required: true, autofocus: true %>
  <br />
  <br />

  <%= f.submit %>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<%= link_to 'Create Item', new_department_item_path(@department) %>
<% @items.each do |items| %>
  <h2><%= items.name %></h2>
  <%= link_to 'Show Item',new_department_item_path(@department) %>
  <%= link_to 'Edit Item', edit_department_item_path(@department, @item) %>
  <% end %>




  
 

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>